[chuck](VM): sporking incoming shred: 3 (cs.ck)...
[chuck](VM): sporking incoming shred: 4 (Random.ck)...
[chuck](VM): sporking incoming shred: 5 (PanFour.ck)...
[chuck](VM): sporking incoming shred: 6 (PanBin.ck)...
[chuck](VM): sporking incoming shred: 7 (PanBin8.ck)...
[chuck](VM): sporking incoming shred: 8 (Pan4.ck)...
[chuck](VM): sporking incoming shred: 9 (Global.ck)...
[chuck](VM): sporking incoming shred: 10 (OSC_Read.ck)...
[chuck](VM): sporking incoming shred: 11 (FeedbackDelay.ck)...
[chuck](VM): sporking incoming shred: 12 (Safe.ck)...
[chuck](VM): sporking incoming shred: 13 (List.ck)...
[chuck](VM): sporking incoming shred: 14 (CList.ck)...
[chuck](VM): sporking incoming shred: 15 (SeqUnit.ck)...
[chuck](VM): sporking incoming shred: 16 (SuperSaw.ck)...
[chuck](VM): sporking incoming shred: 17 (PercEnv.ck)...
[chuck](VM): sporking incoming shred: 18 (Ping.ck)...
[chuck](VM): sporking incoming shred: 19 (Stream)...
[chuck](VM): sporking incoming shred: 20 (ST_choice)...
[chuck](VM): sporking incoming shred: 21 (ST_count)...
[chuck](VM): sporking incoming shred: 22 (ST_count2)...
[chuck](VM): sporking incoming shred: 23 (ST_delay)...
[chuck](VM): sporking incoming shred: 24 (ST_float)...
[chuck](VM): sporking incoming shred: 25 (ST_index)...
[chuck](VM): sporking incoming shred: 26 (ST_indexLin)...
[chuck](VM): sporking incoming shred: 27 (ST_repeat)...
[chuck](VM): sporking incoming shred: 28 (ST_latch)...
[chuck](VM): sporking incoming shred: 29 (ST_timedLatch)...
[chuck](VM): sporking incoming shred: 30 (ST_seq)...
[chuck](VM): sporking incoming shred: 31 (ST_value)...
[chuck](VM): sporking incoming shred: 32 (ST_vase)...
[chuck](VM): sporking incoming shred: 33 (ST_weave)...
[chuck](VM): sporking incoming shred: 34 (ST_tri)...
[chuck](VM): sporking incoming shred: 35 (ST_loop3)...
[chuck](VM): sporking incoming shred: 36 (ST_timed)...
[chuck](VM): sporking incoming shred: 37 (ST_scale)...
[chuck](VM): sporking incoming shred: 38 (ST_scale2)...
[chuck](VM): sporking incoming shred: 39 (ST_line)...
[chuck](VM): sporking incoming shred: 40 (ST_linseg)...
[chuck](VM): sporking incoming shred: 41 (ST_walk)...
[chuck](VM): sporking incoming shred: 42 (ST_walkList)...
[chuck](VM): sporking incoming shred: 43 (ST_smartWalkList)...
[chuck](VM): sporking incoming shred: 44 (ST_mupWalk)...
[chuck](VM): sporking incoming shred: 45 (ST_maskedChoice)...
[chuck](VM): sporking incoming shred: 46 (ST_boundedMupWalk)...
[chuck](VM): sporking incoming shred: 47 (ST_boundedMupResetWalk)...
[chuck](VM): sporking incoming shred: 48 (ST_boundedWalk)...
[chuck](VM): sporking incoming shred: 49 (ST_bumpyWalk)...
[chuck](VM): sporking incoming shred: 50 (ST_bouncyWalk)...
[chuck](VM): sporking incoming shred: 51 (ST_operator)...
[chuck](VM): sporking incoming shred: 52 (ST_sum)...
[chuck](VM): sporking incoming shred: 53 (ST_mup)...
[chuck](VM): sporking incoming shred: 54 (ST_div)...
[chuck](VM): sporking incoming shred: 55 (ST_sub)...
[chuck](VM): sporking incoming shred: 56 (ST_max)...
[chuck](VM): sporking incoming shred: 57 (ST_min)...
[chuck](VM): sporking incoming shred: 58 (ST_rv)...
[chuck](VM): sporking incoming shred: 59 (ST_modulo)...
[chuck](VM): sporking incoming shred: 60 (ST_floor)...
[chuck](VM): sporking incoming shred: 61 (ST_greater)...
[chuck](VM): sporking incoming shred: 62 (ST_bitAnd)...
[chuck](VM): sporking incoming shred: 63 (ST_bitOr)...
[chuck](VM): sporking incoming shred: 64 (ST_bitXor)...
[chuck](VM): sporking incoming shred: 65 (ST_equal)...
[chuck](VM): sporking incoming shred: 66 (ST_exprv)...
[chuck](VM): sporking incoming shred: 67 (ST_pow)...
[chuck](VM): sporking incoming shred: 68 (ST_timedReset)...
[chuck](VM): sporking incoming shred: 69 (ST_reset)...
[chuck](VM): sporking incoming shred: 70 (ST_write)...
[chuck](VM): sporking incoming shred: 71 (ST_readWrite)...
[chuck](VM): sporking incoming shred: 72 (ST_diff)...
[chuck](VM): sporking incoming shred: 73 (ST_onePole)...
[chuck](VM): sporking incoming shred: 74 (ST_tableCap)...
[chuck](VM): sporking incoming shred: 75 (ST_hzPhasor)...
[chuck](VM): sporking incoming shred: 76 (ST_bitShiftL)...
[chuck](VM): sporking incoming shred: 77 (ST_bitShiftR)...
[chuck](VM): sporking incoming shred: 78 (ST_divider)...
[chuck](VM): sporking incoming shred: 79 (ST_q)...
[chuck](VM): sporking incoming shred: 80 (ST_series)...
[chuck](VM): sporking incoming shred: 81 (ST_bus)...
[chuck](VM): sporking incoming shred: 82 (ST_weights)...
[chuck](VM): sporking incoming shred: 83 (ST_wchoice)...
[chuck](VM): sporking incoming shred: 84 (ST_weightStream)...
[chuck](VM): sporking incoming shred: 85 (ST_trigger)...
[chuck](VM): sporking incoming shred: 86 (ST_triggerSend)...
[chuck](VM): sporking incoming shred: 87 (ST_mtof)...
[chuck](VM): sporking incoming shred: 88 (ST_ftom)...
[chuck](VM): sporking incoming shred: 89 (ST_mtor)...
[chuck](VM): sporking incoming shred: 90 (ST_mtosamps)...
[chuck](VM): sporking incoming shred: 91 (ST_sine)...
[chuck](VM): sporking incoming shred: 92 (ST_sineseg)...
[chuck](VM): sporking incoming shred: 93 (ST_ugen)...
[chuck](VM): sporking incoming shred: 94 (ST_clip)...
[chuck](VM): sporking incoming shred: 95 (ST_tanh)...
[chuck](VM): sporking incoming shred: 96 (ST_wave)...
[chuck](VM): sporking incoming shred: 97 (ST_monitor)...
[chuck](VM): sporking incoming shred: 98 (ST_replaceZero)...
[chuck](VM): sporking incoming shred: 99 (Funk.ck)...
[chuck](VM): sporking incoming shred: 100 (TimedFunk.ck)...
[chuck](VM): sporking incoming shred: 101 (ST_funkStream)...
[chuck](VM): sporking incoming shred: 102 (Schedule.ck)...
[chuck](VM): sporking incoming shred: 103 (StreamDict)...
[chuck](VM): sporking incoming shred: 104 (Superchuck)...
[chuck](VM): sporking incoming shred: 105 (WriteStream)...
[chuck](VM): sporking incoming shred: 106 (ST_normStream)...
[chuck](VM): sporking incoming shred: 107 (LineSynth)...
[chuck](VM): sporking incoming shred: 108 (PulseSynth)...
[chuck](VM): sporking incoming shred: 109 (StepSynth)...
[chuck](VM): sporking incoming shred: 110 (FMSynth)...
[chuck](VM): sporking incoming shred: 111 (PingSynth)...
[chuck](VM): sporking incoming shred: 112 (PulsePanSynth)...
[chuck](VM): sporking incoming shred: 113 (StepPanSynth)...
[chuck](VM): sporking incoming shred: 114 (LinePanSynth)...
[chuck](VM): sporking incoming shred: 115 (SinSynth)...
[chuck](VM): sporking incoming shred: 116 (SquareSynth)...
[chuck](VM): sporking incoming shred: 117 (PwmSynth)...
[chuck](VM): sporking incoming shred: 118 (StreamPan)...
[chuck](VM): sporking incoming shred: 119 (StreamHPFilter)...
[chuck](VM): sporking incoming shred: 120 (StreamBPFilter)...
[chuck](VM): sporking incoming shred: 121 (StreamLPFilter)...
[chuck](VM): sporking incoming shred: 122 (StreamFeedbackDelay)...
[chuck](VM): sporking incoming shred: 123 (WriteSchedule)...
[chuck](VM): sporking incoming shred: 124 (MidiStream)...
[chuck](VM): sporking incoming shred: 125 (MidiControlStream)...
[chuck](VM): sporking incoming shred: 126 (StreamNonLinFilter)...
[chuck](VM): sporking incoming shred: 127 (OSCTable)...
[chuck](VM): sporking incoming shred: 128 (st)...
[chuck](VM): sporking incoming shred: 129 (Buses2.ck)...
[chuck](VM): sporking incoming shred: 130 (PanFourBus.ck)...
[chuck](VM): sporking incoming shred: 131 (ReadSSV.ck)...
Input file is " /Users/casperschipper/Google Drive/ChucK/CISP/SINE_CLOUD.lisp
Output file is " output.ck

 mellonfarmer 

('/* (SynthDef(\\simpleSine,{ | freq = 220, duration = 1.0, pan = 0.0 |\tvar sine = SinOsc.ar(freq,0.0);\tvar enveloped = sine * EnvGen.ar( Env.perc(0.01 / freq,duration ), doneAction:2 );\tvar panned = Pan2.ar( enveloped , pos: pan );\tvar dist = panned.tanh * 2;\tOut.ar( 0,  dist * 0.01 );}).send(s);) */(fun freqStep\t(line\t\t(ch (seq -100 -333 true) -1 (seq (latch (st -10) (st 10)) -3033 true) -200 -300 (seq 10 200 30 true))\t\t(t \t\t\t(rv 1 4) \t\t\t(ch 1 2 4))))(fun panStep\t(line\t\t(ch -1.0 -0.1 0.001 0.1 (t (rv -1 1) (ch 0.1 0.001 0.1 1.0)))\t\t(t \t\t\t(ch 1 2 4) \t\t\t(ch 1 2 4))))(sci2 \tsimpleSine\t(t (ch 0.01 0.02 0.001 (rv 0.1 1.0)) (ch 1 2 3))\t:freq (bounded-walk (st 20) (t (rv 10 20000) 1) freqStep)\t:duration (line (ch 0.1 0.01 0.05 0.2 0.01 5.0) (ch 0.1 0.2 0.4 0.8 1.6))\t:pan (bounded-walk -1 1 panStep)\t)', '\n\n,databanaan')
eval : ['fun', 'freqStep', ['line', ['ch', ['seq', -100, -333, 'true'], -1, ['seq', ['latch', ['st', -10], ['st', 10]], -3033, 'true'], -200, -300, ['seq', 10, 200, 30, 'true']], ['t', ['rv', 1, 4], ['ch', 1, 2, 4]]]]
eval : ['line', ['ch', ['seq', -100, -333, 'true'], -1, ['seq', ['latch', ['st', -10], ['st', 10]], -3033, 'true'], -200, -300, ['seq', 10, 200, 30, 'true']], ['t', ['rv', 1, 4], ['ch', 1, 2, 4]]]
eval : line
it is now this:[2]
eval : ['ch', ['seq', -100, -333, 'true'], -1, ['seq', ['latch', ['st', -10], ['st', 10]], -3033, 'true'], -200, -300, ['seq', 10, 200, 30, 'true']]
eval : ch
eval : ['seq', -100, -333, 'true']
eval : seq
eval : -100
eval : -333
eval : true
eval : -1
eval : ['seq', ['latch', ['st', -10], ['st', 10]], -3033, 'true']
eval : seq
eval : ['latch', ['st', -10], ['st', 10]]
eval : latch
it is now this:[2]
eval : ['st', -10]
eval : st
it is now this:[1]
eval : -10
eval : ['st', 10]
eval : st
it is now this:[1]
eval : 10
eval : -3033
eval : true
eval : -200
eval : -300
eval : ['seq', 10, 200, 30, 'true']
eval : seq
eval : 10
eval : 200
eval : 30
eval : true
eval : ['t', ['rv', 1, 4], ['ch', 1, 2, 4]]
eval : t
it is now this:[2]
eval : ['rv', 1, 4]
eval : rv
it is now this:[2]
eval : 1
eval : 4
eval : ['ch', 1, 2, 4]
eval : ch
eval : 1
eval : 2
eval : 4
result:
fun Stream freqStep () {
return 
st.line(
    st.ch([
  st.seq([-100,-333],true),st.st(-1),
  st.seq([
  st.latch(
      st.st(-10),
      st.st(10)),st.st(-3033)],true),st.st(-200),st.st(-300),
  st.seq([10,200,30],true)]),
    st.t(
        st.rv(1,4),
        st.ch([1,2,4])));
}

[chuck](VM): sporking incoming shred: 141 (output.ck)...
